#pragma config(Motor,  port2,           moveMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           claw,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           tilt1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           tilt2,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           swivel,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int driveSpeed;
	driveSpeed=3;
	int direction;
	direction=1;

	while(true)
    //define all variables before the while loop, and put all things that can change at any time below (mostly button presses and motor control)
	{
		//Driving Speed, This is used for allowing us to change the speed of our robot.
		if(vexRT[Btn7U] == 1)
		{driveSpeed = 1;}
		else if(vexRT[Btn7L] == 1)
		{driveSpeed = 2;}
		else if(vexRT[Btn7R] == 1)
		{driveSpeed = 3;}
		else if(vexRT[Btn7D] == 1)
		{driveSpeed = 4;}

		//Driving Direction, lets us drive backwards
		if (vexRT[Btn8U]){direction = 1;}
		if (vexRT[Btn8D]){direction = -1;}

		//Drive motor control

    if(vexRT[Btn5U]){
    	motor[moveMotor] = direction * 127 / driveSpeed;
    }
    else if(vexRT[Btn6U]){
    	motor[moveMotor] = direction * -127 / driveSpeed;
    }
    else{
    	motor[moveMotor]=0;
    }






		//Arm Movement
		motor[swivel] = vexRT[Ch4];
		motor[tilt1] = vexRT[Ch3];
		motor[tilt2] = vexRT[Ch3];

		/*Not working properly
		if(vexRT[Ch3] > -10 && vexRT[Ch3] < 10){
			motor[tilt1] = 10;
			motor[tilt2] = 10;
		}*/

		//Close gripper
		if(vexRT[Btn8L] == 1){
			motor[claw] = -95;
		}
		else if(vexRT[Btn8R] == 1){
			motor[claw] = 95;
		}
	}
}
